### ISSUE TITLE
QMCPy pip upgrade

### ISSUE THREAD

**Issue by mikemccourt** [QMCSoftware/QMCSoftware#194]
When I recently tried to upgrade my QMCPy version to the latest version, I had a complaint
```
Collecting qmcpy
  Using cached qmcpy-0.7.tar.gz (4.0 MB)
Requirement already satisfied: scipy>=1.2.0 in /Users/mccourt/Documents/venv/3.6qmc/lib/python3.6/site-packages (from qmcpy) (1.4.1)
Collecting numpy>=1.18.5
  Using cached numpy-1.19.2-cp36-cp36m-macosx_10_9_x86_64.whl (15.3 MB)
Building wheels for collected packages: qmcpy
  Building wheel for qmcpy (setup.py) ... done
  Created wheel for qmcpy: filename=qmcpy-0.7-cp36-cp36m-macosx_10_13_x86_64.whl size=4144637 sha256=47b68d79a046b32874f3e9caccaaa5596809495e1e62db1574e19ba4b187b71f
  Stored in directory: /Users/mccourt/Library/Caches/pip/wheels/7a/ff/18/8ebc5d37f59e76a8765f2107ea3580489a1b64fb6ce255c4a6
Successfully built qmcpy
ERROR: Error checking for conflicts.
Traceback (most recent call last):
  File "/Users/mccourt/Documents/venv/3.6qmc/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3021, in _dep_map
    return self.__dep_map
  File "/Users/mccourt/Documents/venv/3.6qmc/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mccourt/Documents/venv/3.6qmc/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3012, in _parsed_pkg_info
    return self._pkg_info
  File "/Users/mccourt/Documents/venv/3.6qmc/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mccourt/Documents/venv/3.6qmc/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 512, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "/Users/mccourt/Documents/venv/3.6qmc/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 114, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
  File "/Users/mccourt/Documents/venv/3.6qmc/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 53, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "/Users/mccourt/Documents/venv/3.6qmc/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2736, in requires
    dm = self._dep_map
  File "/Users/mccourt/Documents/venv/3.6qmc/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3023, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/Users/mccourt/Documents/venv/3.6qmc/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3032, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/Users/mccourt/Documents/venv/3.6qmc/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3014, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/Users/mccourt/Documents/venv/3.6qmc/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1420, in get_metadata
    value = self._get(path)
  File "/Users/mccourt/Documents/venv/3.6qmc/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1616, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mccourt/Documents/venv/3.6qmc/lib/python3.6/site-packages/numpy-1.18.4.dist-info/METADATA'
Installing collected packages: numpy, qmcpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.4
    Can't uninstall 'numpy'. No files were found to uninstall.
Successfully installed numpy-1.19.2 qmcpy-0.7
```

I think that, somehow, `pip` is having difficulty cleaning up the directory.  When I created a fresh virtual env and just ran `pip install qmcpy` it worked just fine.  I guess, somehow, some sort of state is coming into existence that I don't fully understand.  I'm going to see if I can figure out what's going on.  Not a blocker, but something that is frustrating.

**Comment by mikemccourt** [comment]
Quick fix, lol.  Just ran `pip install --upgrade pip` and then `pip install qmcpy` no longer made any complaints.

I think, maybe, there was some sort of old permissions set that got reset.  Whatever, doesn't matter.  Just closing this off.
